version: '3.3'
services:
  web:
    build: .
    command: bash -c "sleep 3 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"

