version: '3'

services:
        db:
                image: postgres
                ports:
                        - "5436:5432"
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_DB=db
        backend:
                container_name: django_project
                build: ./django_project
                command: bash -c "
                        sleep 3 &&
                        python3 manage.py makemigrations && python3 manage.py migrate &&
                        python3 manage.py runserver --insecure 0.0.0.0:8000";
                ports:
                        - "8000:8000"
                depends_on:
                        - db
        frontend:
                container_name: vue_project
                build:
                        context: ./vue_project
                        dockerfile: Dockerfile
                command: npm start --start;
                ports:
                        - "8080:8080"
                depends_on:
                        - backend
